### ISSUE TITLE
Deploy the rest of prod infra in dev cluster

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/k8s-resources#1]
- Move all k8s related repos inside here (greenplum, elasticsearch, bitcoin-parser, etc.)
- Add ES and crawlers deployments 
- Configure 2 crawling instances per dist crawler type, reduce requests/min to one request per 10 mins
- Configure ES with index sharing and multiple indexes for better performance (depends on the source)
- Get more nodes for cluster, also update master node or other nodes

**Comment by IsurangaPerera** [comment]
- Added five more nodes to the dev cluster
- Deployed crawlers, Redis and elasticsearch clusters on the dev environment with minimal configurations
