### ISSUE TITLE
Setup Ethereum client in the dev cluster

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/k8s-resources#2]

**Comment by sajithaliyanage** [comment]
Related Commits:
https://github.com/cibr-qcri/k8s-resources/commit/235fe24808c71a58f7cc1fbb569dfc36e4f7effb
https://github.com/cibr-qcri/k8s-resources/commit/943b53f9afe991b019862f43075f729d79320d70
https://github.com/cibr-qcri/k8s-resources/commit/896ab36655134adc9e911d4e234822fed228c36f
https://github.com/cibr-qcri/k8s-resources/commit/c5ab112368b2dd583c9d03db4af1a66b96274de7

**Note**: To run the Ethereum client as an RPC server to parse all the information starting from the genesis block following command needs to be used. 
 ```
geth --gcmode archive --syncmode full --http --http.port=8545 --http.addr=0.0.0.0 --http.api="admin,debug,web3,eth,personal" --http.vhosts="*" --txlookuplimit=0 --vmdebug --log.debug --allow-insecure-unlock'
```

Parameters:
- `--gcmode archive --syncmode full ` for internal transactions
- ` --txlookuplimit=0` for older transaction details
- `--vmdebug --log.debug` for traces
- `--http` enable RPC server

**Comment by boshmaf** [comment]
As discussed, we don't need trace data (internal txes) at the moment, so there is no need to run geth in archive mode (it will be much faster now).
