### ISSUE TITLE
Setup Ethereum parser in the dev cluster

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/k8s-resources#3]
Depends on #2

**Comment by sajithaliyanage** [comment]
Related Commits:
https://github.com/cibr-qcri/k8s-resources/commit/ed9bda1d4c72128702c44dd491dee6a05f58f509
https://github.com/cibr-qcri/k8s-resources/commit/902432d3877d495ca4a883d2ed2d9703ab406c97
https://github.com/cibr-qcri/k8s-resources/commit/1c787ab7fef2453a2c43c22e5f4dd4273565fbe5
